services:
  properties-service:
    build: ./property-service  # Path to your Properties service Dockerfile
    container_name: properties-service
    ports:
      - "8084:8084"

  rentals-service:
    build: ./rental-service # Path to your Rentals service Dockerfile
    container_name: rental-service
    ports:
      - "8085:8085"
    environment:
      PROPERTIES_SERVICE_URL: "http://properties-service:8084"
    depends_on:
      - properties-service

  property-rental-ui:
    build: ./Property-Rental-UI
    container_name: property-rental-ui
    ports:
      - "4200:4200"
    depends_on:
      - properties-service
      - rentals-service